 import "./globals.css";
 import Navbar from "@/Components/Navbar";
 import Footer from "@/Components/Footer";
 import { ProductProvider } from "@/context/ProductContext";
export const metadata = {
  title: "prectice for interviww",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Navbar />
        <ProductProvider>
        {children}
        </ProductProvider>

        <Footer />
      </body>
    </html>
  );
}
 
