import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
// import { ProductProvider } from "@/context/ProductContext";
 
export const metadata = {
  title: "practice for interview",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        
        {/* ✅ Wrap with both contexts */}
        {/* <ProductProvider> */}
             {children}
         {/* </ProductProvider> */}
 
      </body>
    </html>
  );
}
